---
title: "Advent of Code 2021: Day 3"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(tidyverse)
library(rvest)
library(httr)
cookie <- read.csv(here::here("content/Advent of Code/posts/cookie.csv"))
```

`r read_html("https://adventofcode.com/2021/day/3") %>% 
  html_element(".day-desc") %>% 
  paste(collapse = '\n') `
  
```{r}
input <- GET("https://adventofcode.com/2021/day/3/input", 
           set_cookies(`_ga`=cookie$Input[1], 
                         `_gid`=cookie$Input[2],
                         `session`=cookie$Input[3]))

input_text <- content(input, "text") %>% 
  read_lines() %>% 
  as_tibble()
```

# Part 1 solution

First, find the number of bits for each entry. Then separate out so I can find if 1 or 0 are most common. Then, construct delta and epsilon by comparing if `0` or `1` are most common. Convert from binary to decimal using the base function `strtoi`:

```{r, echo = T}
n <- nchar(input_text$value)

# 12 bits

sol_1 <- input_text 

for (i in 1:12){
  col <- paste("col_", i, sep = "")
  sol_1[[col]] = substr(sol_1$value, i, i)
}

sol_1_2 <- sol_1 %>% 
  select(-value) %>% 
  pivot_longer(cols = col_1:col_12) %>% 
  group_by(value, name) %>% 
  summarize(count = n()) %>% 
# order "correctly" by number
  arrange(order(gtools::mixedorder(name))) %>% 
  pivot_wider(names_from = value, values_from = count) %>% 
  mutate(delta = ifelse(`0` > `1`, 0, 1)) %>% 
  mutate(epsilon = ifelse(`0` < `1`, 0, 1))

knitr::kable(sol_1_2)

# delta = most common
delta <- do.call(paste0, c(sol_1_2["delta"], collapse = ""))
delta <- strtoi(delta, 2)

# epsilon
epsilon <- do.call(paste0, c(sol_1_2["epsilon"], collapse = ""))
epsilon <- strtoi("010001000011", 2)

delta * epsilon
```


```{r, eval = T}
part2 <- GET("https://adventofcode.com/2021/day/3#part2", 
           set_cookies(`_ga`=cookie$Input[1], 
                         `_gid`=cookie$Input[2],
                         `session`=cookie$Input[3]))
```

`r read_html(part2) %>% 
  html_element("p + .day-desc") %>% 
  paste(collapse = '\n')`

# Part 2 solution


```{r, echo = T, eval = F}
#initial long way ...

sol_2 <- input_text %>% 
  mutate(col_1 = as.numeric(substr(value, 1, 1))) %>% 
  mutate(ox_gen1 = ifelse(mean(col_1) >= 0.5, 1, 0)) %>% 
  filter(col_1 == ox_gen1) %>%   
  mutate(col_2 = as.numeric(substr(value, 2, 2))) %>% 
  mutate(ox_gen2 = ifelse(mean(col_2) >= 0.5, 1, 0)) %>% 
  filter(col_2 == ox_gen2) %>%   
  mutate(col_3 = as.numeric(substr(value, 3, 3))) %>% 
  mutate(ox_gen3 = ifelse(mean(col_3) >= 0.5, 1, 0)) %>% 
  filter(col_3 == ox_gen3) %>%   
  etc ...

sol_2 <- input_text %>% 
  mutate(col_1 = as.numeric(substr(value, 1, 1))) %>% 
  mutate(co_scrub1 = ifelse(mean(col_1) < 0.5, 1, 0)) %>% 
  filter(col_1 == co_scrub1) %>%   
  mutate(col_2 = as.numeric(substr(value, 2, 2))) %>% 
  mutate(co_scrub2 = ifelse(mean(col_2) < 0.5, 1, 0)) %>% 
  filter(col_2 == co_scrub2) %>%   
  mutate(col_3 = as.numeric(substr(value, 3, 3))) %>% 
  mutate(co_scrub3 = ifelse(mean(col_3) < 0.5, 1, 0)) %>% 
  filter(col_3 == co_scrub3) %>%   
  mutate(col_4 = as.numeric(substr(value, 4, 4))) %>% 
  mutate(co_scrub4 = ifelse(mean(col_4) < 0.5, 1, 0)) %>% 
  filter(col_4 == co_scrub4) ...
```

```{r, echo = T, eval = T}
# using a loop
sol_2_1 <- input_text
for (i in 1:12){
    col <- paste("col_", i, sep = "")
    ox_gen <- paste("ox_gen_", i, sep = "")
    sol_2_1 <- sol_2_1 %>% 
      mutate(col = as.numeric(substr(value, i, i))) %>% 
      mutate(ox_gen = ifelse(mean(col) >= 0.5, 1, 0)) %>% 
      filter(col == ox_gen)
}
ox_gen <- sol_2_1$value

# while length(value) > 1:

sol_2_2 <- input_text
for (i in 1:12){
  while (length(sol_2_2$value) > 1) {
    col <- paste("col_", i, sep = "")
    co_scrub <- paste("co_scrub_", i, sep = "")
  sol_2_2 <- sol_2_2 %>% 
  mutate(col = as.numeric(substr(value, i, i))) %>% 
  mutate(co_scrub = ifelse(mean(col) < 0.5, 1, 0)) %>% 
  filter(col == co_scrub) 
  if ((length(sol_2_1$value) = 1)) {
      break
    }
  }
}
co_scrub <- sol_2_2$value

ox_gen <- strtoi(as.numeric(ox_gen), 2)

co_scrub <- strtoi(as.numeric(co_scrub), 2)

ox_gen * co_scrub
```


