<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Advent of Code 2021: Day 3 | Kaitlin Maciejewski</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    <script src="https://kit.fontawesome.com/2572d6fa3c.js" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li>
        <a href="/">Home</a>
      </li>
      
      <li>
        <a href="/about/">About</a>
      </li>
      
      <li>
        <a href="/projects/">Projects</a>
      </li>
      
      <li>
        <a href="/code-blog/">Code Blog</a>
      </li>
      
      
      <li class="navbar-icon"><a href="mailto:katemac68@gmail.com"><i class="fas fa-envelope"></i></a></li>
      
      <li class="navbar-icon"><a href="https://github.com/k-maciejewski/"><i class="fab fa-github"></i></a></li>
      
      <li class="navbar-icon"><a href="https://www.linkedin.com/in/kmaciejewski/"><i class="fab fa-linkedin"></i></a></li>
      
      <li class="navbar-icon"><a href="https://orcid.org/0000-0002-6387-582X"><i class="fab fa-orcid"></i></a></li>
      
      <li class="navbar-icon"><a href="https://www.researchgate.net/profile/Kaitlin-Maciejewski"><i class="fab fa-researchgate"></i></a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title">Advent of Code 2021: Day 3</span></h1>


</div>

<main>

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<article class="day-desc">
<h2>
— Day 3: Binary Diagnostic —
</h2>
<p>
The submarine has been making some <span title="Turns out oceans are heavy.">odd creaking noises</span>, so you ask it to produce a diagnostic report just in case.
</p>
<p>
The diagnostic report (your puzzle input) consists of a list of binary numbers which, when decoded properly, can tell you many useful things about the conditions of the submarine. The first parameter to check is the <em>power consumption</em>.
</p>
<p>
You need to use the binary numbers in the diagnostic report to generate two new binary numbers (called the <em>gamma rate</em> and the <em>epsilon rate</em>). The power consumption can then be found by multiplying the gamma rate by the epsilon rate.
</p>
<p>
Each bit in the gamma rate can be determined by finding the <em>most common bit in the corresponding position</em> of all numbers in the diagnostic report. For example, given the following diagnostic report:
</p>
<pre><code>00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
</code></pre>
<p>
Considering only the first bit of each number, there are five <code>0</code> bits and seven <code>1</code> bits. Since the most common bit is <code>1</code>, the first bit of the gamma rate is <code>1</code>.
</p>
<p>
The most common second bit of the numbers in the diagnostic report is <code>0</code>, so the second bit of the gamma rate is <code>0</code>.
</p>
<p>
The most common value of the third, fourth, and fifth bits are <code>1</code>, <code>1</code>, and <code>0</code>, respectively, and so the final three bits of the gamma rate are <code>110</code>.
</p>
<p>
So, the gamma rate is the binary number <code>10110</code>, or <code><em>22</em></code> in decimal.
</p>
<p>
The epsilon rate is calculated in a similar way; rather than use the most common bit, the least common bit from each position is used. So, the epsilon rate is <code>01001</code>, or <code><em>9</em></code> in decimal. Multiplying the gamma rate (<code>22</code>) by the epsilon rate (<code>9</code>) produces the power consumption, <code><em>198</em></code>.
</p>
<p>
Use the binary numbers in your diagnostic report to calculate the gamma rate and epsilon rate, then multiply them together. <em>What is the power consumption of the submarine?</em> (Be sure to represent your answer in decimal, not binary.)
</p>
</article>
<div id="part-1-solution" class="section level1">
<h1>Part 1 solution</h1>
<p>First, find the number of bits for each entry. Then separate out so I can find if 1 or 0 are most common. Then, construct delta and epsilon by comparing if <code>0</code> or <code>1</code> are most common. Convert from binary to decimal using the base function <code>strtoi</code>:</p>
<pre class="r"><code>n &lt;- nchar(input_text$value)

# 12 bits

sol_1 &lt;- input_text 

for (i in 1:12){
  col &lt;- paste(&quot;col_&quot;, i, sep = &quot;&quot;)
  sol_1[[col]] = substr(sol_1$value, i, i)
}

sol_1_2 &lt;- sol_1 %&gt;% 
  select(-value) %&gt;% 
  pivot_longer(cols = col_1:col_12) %&gt;% 
  group_by(value, name) %&gt;% 
  summarize(count = n()) %&gt;% 
# order &quot;correctly&quot; by number
  arrange(order(gtools::mixedorder(name))) %&gt;% 
  pivot_wider(names_from = value, values_from = count) %&gt;% 
  mutate(delta = ifelse(`0` &gt; `1`, 0, 1)) %&gt;% 
  mutate(epsilon = ifelse(`0` &lt; `1`, 0, 1))

knitr::kable(sol_1_2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">0</th>
<th align="right">1</th>
<th align="right">delta</th>
<th align="right">epsilon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">col_1</td>
<td align="right">489</td>
<td align="right">511</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">col_2</td>
<td align="right">502</td>
<td align="right">498</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">col_3</td>
<td align="right">496</td>
<td align="right">504</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">col_4</td>
<td align="right">487</td>
<td align="right">513</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">col_5</td>
<td align="right">477</td>
<td align="right">523</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">col_6</td>
<td align="right">513</td>
<td align="right">487</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">col_7</td>
<td align="right">498</td>
<td align="right">502</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">col_8</td>
<td align="right">489</td>
<td align="right">511</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">col_9</td>
<td align="right">483</td>
<td align="right">517</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">col_10</td>
<td align="right">487</td>
<td align="right">513</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">col_11</td>
<td align="right">518</td>
<td align="right">482</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">col_12</td>
<td align="right">502</td>
<td align="right">498</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<pre class="r"><code># delta = most common
delta &lt;- do.call(paste0, c(sol_1_2[&quot;delta&quot;], collapse = &quot;&quot;))
delta &lt;- strtoi(delta, 2)

# epsilon
epsilon &lt;- do.call(paste0, c(sol_1_2[&quot;epsilon&quot;], collapse = &quot;&quot;))
epsilon &lt;- strtoi(&quot;010001000011&quot;, 2)

delta * epsilon</code></pre>
<pre><code>## [1] 3277364</code></pre>
<article class="day-desc">
<h2 id="part2">
— Part Two —
</h2>
<p>
Next, you should verify the <em>life support rating</em>, which can be determined by multiplying the <em>oxygen generator rating</em> by the <em>CO2 scrubber rating</em>.
</p>
<p>
Both the oxygen generator rating and the CO2 scrubber rating are values that can be found in your diagnostic report - finding them is the tricky part. Both values are located using a similar process that involves filtering out values until only one remains. Before searching for either rating value, start with the full list of binary numbers from your diagnostic report and <em>consider just the first bit</em> of those numbers. Then:
</p>
<ul>
<li>
Keep only numbers selected by the <em>bit criteria</em> for the type of rating value for which you are searching. Discard numbers which do not match the bit criteria.
</li>
<li>
If you only have one number left, stop; this is the rating value for which you are searching.
</li>
<li>
Otherwise, repeat the process, considering the next bit to the right.
</li>
</ul>
<p>
The <em>bit criteria</em> depends on which type of rating value you want to find:
</p>
<ul>
<li>
To find <em>oxygen generator rating</em>, determine the <em>most common</em> value (<code>0</code> or <code>1</code>) in the current bit position, and keep only numbers with that bit in that position. If <code>0</code> and <code>1</code> are equally common, keep values with a <code><em>1</em></code> in the position being considered.
</li>
<li>
To find <em>CO2 scrubber rating</em>, determine the <em>least common</em> value (<code>0</code> or <code>1</code>) in the current bit position, and keep only numbers with that bit in that position. If <code>0</code> and <code>1</code> are equally common, keep values with a <code><em>0</em></code> in the position being considered.
</li>
</ul>
<p>
For example, to determine the <em>oxygen generator rating</em> value using the same example diagnostic report from above:
</p>
<ul>
<li>
Start with all 12 numbers and consider only the first bit of each number. There are more <code>1</code> bits (7) than <code>0</code> bits (5), so keep only the 7 numbers with a <code>1</code> in the first position: <code>11110</code>, <code>10110</code>, <code>10111</code>, <code>10101</code>, <code>11100</code>, <code>10000</code>, and <code>11001</code>.
</li>
<li>
Then, consider the second bit of the 7 remaining numbers: there are more <code>0</code> bits (4) than <code>1</code> bits (3), so keep only the 4 numbers with a <code>0</code> in the second position: <code>10110</code>, <code>10111</code>, <code>10101</code>, and <code>10000</code>.
</li>
<li>
In the third position, three of the four numbers have a <code>1</code>, so keep those three: <code>10110</code>, <code>10111</code>, and <code>10101</code>.
</li>
<li>
In the fourth position, two of the three numbers have a <code>1</code>, so keep those two: <code>10110</code> and <code>10111</code>.
</li>
<li>
In the fifth position, there are an equal number of <code>0</code> bits and <code>1</code> bits (one each). So, to find the <em>oxygen generator rating</em>, keep the number with a <code>1</code> in that position: <code>10111</code>.
</li>
<li>
As there is only one number left, stop; the <em>oxygen generator rating</em> is <code>10111</code>, or <code><em>23</em></code> in decimal.
</li>
</ul>
<p>
Then, to determine the <em>CO2 scrubber rating</em> value from the same example above:
</p>
<ul>
<li>
Start again with all 12 numbers and consider only the first bit of each number. There are fewer <code>0</code> bits (5) than <code>1</code> bits (7), so keep only the 5 numbers with a <code>0</code> in the first position: <code>00100</code>, <code>01111</code>, <code>00111</code>, <code>00010</code>, and <code>01010</code>.
</li>
<li>
Then, consider the second bit of the 5 remaining numbers: there are fewer <code>1</code> bits (2) than <code>0</code> bits (3), so keep only the 2 numbers with a <code>1</code> in the second position: <code>01111</code> and <code>01010</code>.
</li>
<li>
In the third position, there are an equal number of <code>0</code> bits and <code>1</code> bits (one each). So, to find the <em>CO2 scrubber rating</em>, keep the number with a <code>0</code> in that position: <code>01010</code>.
</li>
<li>
As there is only one number left, stop; the <em>CO2 scrubber rating</em> is <code>01010</code>, or <code><em>10</em></code> in decimal.
</li>
</ul>
<p>
Finally, to find the life support rating, multiply the oxygen generator rating (<code>23</code>) by the CO2 scrubber rating (<code>10</code>) to get <code><em>230</em></code>.
</p>
<p>
Use the binary numbers in your diagnostic report to calculate the oxygen generator rating and CO2 scrubber rating, then multiply them together. <em>What is the life support rating of the submarine?</em> (Be sure to represent your answer in decimal, not binary.)
</p>
</article>
</div>
<div id="part-2-solution" class="section level1">
<h1>Part 2 solution</h1>
<pre class="r"><code># using sol_1:
# most common for 1 is 1
# filter to col_1 = 1

sol_2 &lt;- input_text %&gt;% 
  mutate(col_1 = as.numeric(substr(value, 1, 1))) %&gt;% 
  mutate(ox_gen1 = ifelse(mean(col_1) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_1 == ox_gen1) %&gt;%   
  mutate(col_2 = as.numeric(substr(value, 2, 2))) %&gt;% 
  mutate(ox_gen2 = ifelse(mean(col_2) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_2 == ox_gen2) %&gt;%   
  mutate(col_3 = as.numeric(substr(value, 3, 3))) %&gt;% 
  mutate(ox_gen3 = ifelse(mean(col_3) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_3 == ox_gen3) %&gt;%   
  mutate(col_4 = as.numeric(substr(value, 4, 4))) %&gt;% 
  mutate(ox_gen4 = ifelse(mean(col_4) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_4 == ox_gen4) %&gt;%   
  mutate(col_5 = as.numeric(substr(value, 5, 5))) %&gt;% 
  mutate(ox_gen5 = ifelse(mean(col_5) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_5 == ox_gen5) %&gt;%   
  mutate(col_6 = as.numeric(substr(value, 6, 6))) %&gt;% 
  mutate(ox_gen6 = ifelse(mean(col_6) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_6 == ox_gen6) %&gt;%   
  mutate(col_7 = as.numeric(substr(value, 7, 7))) %&gt;% 
  mutate(ox_gen7 = ifelse(mean(col_7) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_7 == ox_gen7) %&gt;%   
  mutate(col_8 = as.numeric(substr(value, 8, 8))) %&gt;% 
  mutate(ox_gen8 = ifelse(mean(col_8) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_8 == ox_gen8) %&gt;%   
  mutate(col_9 = as.numeric(substr(value, 9, 9))) %&gt;% 
  mutate(ox_gen9 = ifelse(mean(col_9) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_9 == ox_gen9) %&gt;%   
  mutate(col_10 = as.numeric(substr(value, 10, 10))) %&gt;% 
  mutate(ox_gen10 = ifelse(mean(col_10) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_10 == ox_gen10) %&gt;%   
  mutate(col_11 = as.numeric(substr(value, 11, 11))) %&gt;% 
  mutate(ox_gen11 = ifelse(mean(col_11) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_11 == ox_gen11) %&gt;%   
  mutate(col_12 = as.numeric(substr(value, 12, 12))) %&gt;% 
  mutate(ox_gen12 = ifelse(mean(col_12) &gt;= 0.5, 1, 0)) %&gt;% 
  filter(col_12 == ox_gen12)

ox_gen &lt;- sol_2$value

# while length(value) &gt; 1:
sol_2 &lt;- input_text %&gt;% 
  mutate(col_1 = as.numeric(substr(value, 1, 1))) %&gt;% 
  mutate(co_scrub1 = ifelse(mean(col_1) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_1 == co_scrub1) %&gt;%   
  mutate(col_2 = as.numeric(substr(value, 2, 2))) %&gt;% 
  mutate(co_scrub2 = ifelse(mean(col_2) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_2 == co_scrub2) %&gt;%   
  mutate(col_3 = as.numeric(substr(value, 3, 3))) %&gt;% 
  mutate(co_scrub3 = ifelse(mean(col_3) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_3 == co_scrub3) %&gt;%   
  mutate(col_4 = as.numeric(substr(value, 4, 4))) %&gt;% 
  mutate(co_scrub4 = ifelse(mean(col_4) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_4 == co_scrub4) %&gt;%   
  mutate(col_5 = as.numeric(substr(value, 5, 5))) %&gt;% 
  mutate(co_scrub5 = ifelse(mean(col_5) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_5 == co_scrub5) %&gt;%   
  mutate(col_6 = as.numeric(substr(value, 6, 6))) %&gt;% 
  mutate(co_scrub6 = ifelse(mean(col_6) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_6 == co_scrub6) %&gt;%   
  mutate(col_7 = as.numeric(substr(value, 7, 7))) %&gt;% 
  mutate(co_scrub7 = ifelse(mean(col_7) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_7 == co_scrub7) %&gt;%   
  mutate(col_8 = as.numeric(substr(value, 8, 8))) %&gt;% 
  mutate(co_scrub8 = ifelse(mean(col_8) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_8 == co_scrub8) %&gt;%   
  mutate(col_9 = as.numeric(substr(value, 9, 9))) %&gt;% 
  mutate(co_scrub9 = ifelse(mean(col_9) &lt; 0.5, 1, 0)) %&gt;% 
  filter(col_9 == co_scrub9) 

co_scrub &lt;- sol_2$value

ox_gen &lt;- strtoi(as.numeric(ox_gen), 2)

co_scrub &lt;- strtoi(as.numeric(co_scrub), 2)

ox_gen * co_scrub</code></pre>
</div>

</main>

  <footer>
  <hr>

<footer style="background-color:#eee;">
built with <a href="https://github.com/rstudio/blogdown">blogdown</a>, theme adapted from <a href="https://xmin.yihui.org"> Yihui's hugo-xmin </a>
</footer>
  
  </footer>
  </body>
</html>

